### ISSUE TITLE
Rules of Contributing

### ISSUE THREAD

**Issue by PJUllrich** [bundesAPI/sofortmassnahmen#13]
Bitte korrigiert mich wenn ich nur zu doof war es zu finden, aber leider konnte ich bisher keine Informationen darüber finden wie man zum `bundesAPI` beitragen kann. 

Bei existierenden Projekten nehme ich an, dass ein PR gewünscht ist, aber wie können neue Projekte begonnen werden? Soll man ein eigenes Repo erstellen und dieses dann an die `bundesAPI`-Organisation übertragen? Oder soll ein Projektvorschlag im `sofortmassnahmen`-Repo als Issue erstellt werden und die `bundesAPI`-Organisation erstellt dann ein neues Repo falls der Vorschlag akzeptiert wird? 

Ich möchte deswegen vorschlagen eine `Contributing.md` o.ä. zu erstellen, um den Einstieg für neue Contributor zu erleichtern.

**Comment by LilithWittmann** [comment]
Hier ein Vorschlag: https://github.com/bundesAPI/sofortmassnahmen/pull/15/files
Freue mich auf Feedback

**Comment by PJUllrich** [comment]
Toppie 👍 Dann schließe ich mal dieses issue.
