### ISSUE TITLE
Warnhinweise des Bundeskriminalamts (BKA) als JSON

### ISSUE THREAD

**Issue by Lukas2112** [bundesAPI/sofortmassnahmen#14]
Ich denke, dass es sehr viel Sinn ergäbe, wenn es die Warnhinweise des BKA die unter https://www.bka.de/DE/IhreSicherheit/Warnhinweise/warnhinweise_node.html zu finden sind, als JSON gäbe. 

Mein Hintergedanke dabei wäre gewesen, dass die Landespolizeistellen anhand dessen für ihre Dienststellen entsprechende Software schreiben lassen könnten, die die Hinweise auf einem Monitor (abwechselt mit den aktuellen Fahndungen des BKA?) in den Dienststellen anzeigt.

**Comment by LilithWittmann** [comment]
Gibt die App der Polizei BB. Da sollte man die API rausfriemeln können.

**Comment by Lukas2112** [comment]
Gilt dies auch für die Fahndungen des BKA?

**Comment by LilithWittmann** [comment]
@Lukas2112 die werden über die App auch ausgespielt.

**Comment by Hypercookie** [comment]
@LilithWittmann zeigt die app nicht nur "lokale" meldungen/fahndungen? Unter #5 wäre nen scraper für die BKA seite verlinkt.

**Comment by LilithWittmann** [comment]
@Hypercookie ja da gibts die Bundesweiten per suchfilter.
