### ISSUE TITLE
Luftqualität für ganz Deutschland als JSON

### ISSUE THREAD

**Issue by Lukas2112** [bundesAPI/sofortmassnahmen#17]
https://www.umweltbundesamt.de/daten/luft/luftdaten/luftqualitaet/eJzrWJSSuMrIwMhQ18BC19BwUUnmQvNFeakLFhWXLFic4lYElzMwWZwSko-sNLeKY1FuctPinMSS0w6eJUxH3upuXJyTl37aQaVSgoGBgREAIkMhMA==

**Comment by LilithWittmann** [comment]
Möchte das jemand dokumentieren? Bitte bescheid sagen, dann lege ich Repo und Website an.

**Comment by pixeldesu** [comment]
@LilithWittmann 👋 Ich hab mir die Schnittstellen angesehen und würde mich darum kümmern!

**Comment by LilithWittmann** [comment]
@pixeldesu Nice! Hier ein Repo: https://github.com/bundesAPI/luftqualitaet-api. Du bist als Maintainer invited.

**Comment by pixeldesu** [comment]
Ziemlich lustig was sich genau so ergibt wenn man mit der Doku fertig wird.

Es gibt schon eine Schnittstellenbeschreibung von dem Umweltbundesamt selbst, sogar nur ein Pfadsegment weiter als die eigentliche Seite: https://www.umweltbundesamt.de/daten/luft/luftdaten/doc

und ne OAS haben sie auch: https://www.umweltbundesamt.de/sites/all/modules/custom/w21_air_data/doc/uba-air-data-api_public.yaml

Info von bundesAPI/luftqualitaet-api#1
