### ISSUE TITLE
Ladesäulenregister (Bundesnetzagentur)

### ISSUE THREAD

**Issue by vollkorntomate** [bundesAPI/sofortmassnahmen#22]
Die Bundesnetzagentur betreibt eine [interaktive Karte für Ladesäulen](https://www.bundesnetzagentur.de/DE/Sachgebiete/ElektrizitaetundGas/Unternehmen_Institutionen/E-Mobilitaet/Ladesaeulenkarte/start.html) für Elektrofahrzeuge, die auf öffentliche Daten unter der CC BY 4.0 Lizenz zurückgreift. Die Daten müssen aufgrund der Ladesäulenverordnung (LSV) von den Betreibern der Ladepunkte an die Bundesnetzagentur gemeldet werden.

Gehostet und bereitgestellt wird die API von ESRI's ArcGIS System, wo sie bereits [rudimentär dokumentiert](https://services6.arcgis.com/6jU7RmJig2Wwo1b0/ArcGIS/rest/services/Ladesaeulenregister/FeatureServer/7) ist.

Die API einen Endpunkt für die Daten zu den Ladesäulen (https://services6.arcgis.com/6jU7RmJig2Wwo1b0/arcgis/rest/services/Ladesaeulenregister/FeatureServer/7/query) und weitere für Zusammenfassungen auf Landkreis- und Bundesländerebene.

Bei der Dokumentation helfe ich sehr gerne aus!

**Comment by LilithWittmann** [comment]
Sehr coole Idee. Ich habe mal ein Repository erstellt und Dir write access gegeben @vollkorntomate https://github.com/bundesAPI/ladestationen-api
