### ISSUE TITLE
Aufnahme der API des statistischen Bundesamtes 

### ISSUE THREAD

**Issue by vmaster89** [bundesAPI/sofortmassnahmen#23]
Die API des statischen Bundesamtes könnte noch aufgenommen werden. Habe ich vllt. übersehen: https://www.destatis.de/DE/Service/OpenData/genesis-api-webservice-oberflaeche.html

**Comment by Hypercookie** [comment]
hätte ne openapi specification. Wohin damit?

**Comment by LilithWittmann** [comment]
@Hypercookie yaaay! Cool!
Bitte hier hin:
https://github.com/bundesAPI/destatis-api
