### ISSUE TITLE
Meta: Labelling

### ISSUE THREAD

**Issue by pixeldesu** [bundesAPI/sofortmassnahmen#26]
_Mehr Labels, weil Labels gut sind™️_

> Lustigerweise sind, während ich diesen Gedanken hatte sowieso schon Labels in Benutzung gegangen

* **Plattform-Labels:** Web/Mobil (vorallem wichtig im Research, Thema mitmproxies etc.)
* **"Aufgaben" (?)-Labels:** Ob es notwendig ist nur zu dokumentieren, oder einen Scraper in `deutschland` einzubauen.
* _weiteres, was man noch grob kategorisieren könnte_

Das soll natürlich keinen absoluten Label-Wahnsinn auslösen, aber Personen erlauben eher das zu finden was ihnen persönlich mehr an Aufgaben zuspricht.

**Comment by LilithWittmann** [comment]
Erledigt ✅
