### ISSUE TITLE
Bundesnetzagentur: SMARD

### ISSUE THREAD

**Issue by LilithWittmann** [bundesAPI/sofortmassnahmen#28]
Bundesnetzagentur Strommarktdaten: https://www.smard.de/en

**Comment by lukaspanni** [comment]
Ich werde etwas dran arbeiten, da ich die API sowieso benutzen möchte

**Comment by LilithWittmann** [comment]
@lukaspanni sehr cool! Danke! https://github.com/bundesAPI/smard-api

**Comment by LilithWittmann** [comment]
So jetzt auch mit Domain: https://smard.api.bund.dev/
