### ISSUE TITLE
Umweltbundesamt: Meeresumweltdatenbank (MUDAB)

### ISSUE THREAD

**Issue by pixeldesu** [bundesAPI/sofortmassnahmen#29]
> In der MUDAB werden physikalische, hydrographische sowie hydrochemische und biologische Parameter der Meeresumwelt erfasst. Die zentrale Datenbank dient u.a. der Unterstützung der Tätigkeiten der Bund/Länder-Arbeitsgemeinschaft Nord- und Ostsee (BLANO). Darüber hinaus leistet die MUDAB einen wesentlichen Beitrag im Rahmen der von Deutschland eingegangenen internationalen Verpflichtungen zur Bereitstellung von Umweltdaten für den Meeresschutz. U.a. liefert die Meeresumweltdatenbank die Messdaten zur Unterstützung des internationalen "Übereinkommen Oslo/Paris zur Überwachung der Nordsee" (OSPAR) und der "Helsinki-Konvention zur Überwachung der Ostsee" (HELCOM). Nicht zuletzt leistet die MUDAB einen wesentlichen Beitrag zur "Umweltberichterstattung Meer" (SOE-Report) an die Europäische Umweltagentur in Kopenhagen (EEA).

https://geoportal.bafg.de/MUDABAnwendung/

**Comment by LilithWittmann** [comment]
@pixeldesu Cool, magst Du dich darum kümmern?

**Comment by pixeldesu** [comment]
@LilithWittmann Generell ja, ich bin aber noch nicht mit den Schnittstellen für die Luftqualität fertig (Daten dafür hab ich schon, nur die OAS schreibt sich leider nicht selbst)

Wenn ich damit fertig bin und bis dahin hat sich niemand dafür erklärt, dann ja, sonst lasse ich erstmal noch anderen den Vortritt 💪

**Comment by LilithWittmann** [comment]
@pixeldesu habe mal ein Repo angelegt. https://github.com/bundesAPI/mudab-api

**Comment by Deichindianer** [comment]
Hab mich grade mal daran gesetzt die API zumindest rudimentär durchzuschauen, https://github.com/bundesAPI/mudab-api/pull/1/files 

Die requests sind zum Glück alle relativ einfach zu modellieren, da die Syntax für alle endpoints gleich zu seinen scheint.

**Comment by LilithWittmann** [comment]
https://mudab.api.bund.dev/
