### ISSUE TITLE
Warnungen auf lebensmittelwarnung.de

### ISSUE THREAD

**Issue by Bendodroid** [bundesAPI/sofortmassnahmen#33]
# https://www.lebensmittelwarnung.de/bvl-lmw-de/

Ich habe ein wenig an den URLs rumgespielt, konnte aber keine API-Endpunkte finden, aus denen ein schönes JSON rausfällt.
Es gibt wohl nur direkt das fertige HTML und die RSS Feeds. Man muss die Meldungen wohl aus einem der beiden rausdoktern.

Könnte aber gut sein, dass ich etwas offensichtliches übersehen habe, jmd. mit mehr Erfahrung beim Behörden-reverse-engineering mag da mehr Erfolg haben.

Soweit ich das bisher erkennen konnte ist die URL für die Website wie folgt aufgebaut:
```text
/bvl-lmw-de/liste/alle/deutschlandweit/100/0
                   |          |         |  |
                   |          |         |  --> Seite 0-...
                   |          |         |  
                   |          |         --> Anzahl Ergebnisse pro Seite
                   |          |
                   |          --> Bundesland
                   |
                   --> Kategorie
```
#### Mögliche Werte:

Kategorie: `alle`, `lebensmittel`, `kosmetische+mittel`, `bedarfsgegenstaende`

Bundesland: `deutschlandweit`, `baden-wuerttemberg`, `bayern`, `berlin`, `brandenburg`, `bremen`, `hamburg`, `hessen`, `mecklenburgvorpommern`, `niedersachsen`, `nordrheinwestfalen`, `rheinlandpfalz`, `saarland`, `sachsen`, `sachsenanhalt`, `schleswigholstein`, `thueringen`

**Comment by LilithWittmann** [comment]
Also es gibt noch die App aus Bayern (Verbraucher Schutz) da könnte man mal reinschauen. Ansonsten könnte man auch einfach den RSS zu JSON machen über API Proxy…

**Comment by kaiwinter** [comment]
> RSS zu JSON machen über API Proxy…

Das müsste man irgendwo selbst hosten, oder? Hast du dafür eine Idee?

Aus der Verbraucher Schutz App wird dieser REST-Endpunkt verwendet: `https://megov.bayern.de/verbraucherschutz/baystmuv-verbraucherinfo/rest/api`
Die Daten stammen dann also nicht direkt von lebensmittelwarnung.de, außerdem wird ein API-Key benötigt.
<details>
<summary>Beispiel-Antwort</summary>

```JSON
{
    "response": {
        "docs": [
            {
                "_type": ".FoodWarning",
                "archived": false,
                "id": 4592,
                "link": "https://www.lebensmittelwarnung.de/bvl-lmw-de/detail/lebensmittel/69401",
                "publishedDate": 1629891477000,
                "title": "Solevita Hanf Tee 0,75 l",
                "warning": "Es wurde ein erhöhter Gehalt an Tetrahydrocannabinol (THC) festgestellt.",
                "affectedStates": [
                    "Baden-Württemberg",
                    "Bayern",
                    "Berlin",
                    "Bremen",
                    "Hamburg",
                    "Hessen",
                    "Mecklenburg-Vorpommern",
                    "Nordrhein-Westfalen",
                    "Rheinland-Pfalz",
                    "Saarland",
                    "Sachsen",
                    "Sachsen-Anhalt",
                    "Schleswig-Holstein",
                    "Thüringen"
                ],
                "product": {
                    "_type": ".FoodWarning$Food",
                    "designation": "<div>\n  Solevita Hanf Tee 0,75 l\n <br> \n</div>",
                    "imageUrls": [
                        "https://www.lebensmittelwarnung.de/bvl-lmw-de/opensaga/attachment/781be82c-94d1-4860-8829-33e751df406e/Pfanner.PNG"
                    ],
                    "manufacturer": "Hermann PF Getränke GmbH Vertrieben über die Fa. Lidl"
                }
            }
        ],
        "numFound": 4189
    }
}
```
</details>

**Comment by auchtetraborat** [comment]
Die Daten aus deinem curl mit "food" sind exakt die gleichen aus dem RSS-Feed, auch in gleicher Reihenfolge im Output.

Die Daten aus dem curl mit "product" sind im Wesentlichen von [Datenbank "Gefährliche Produkte in Deutschland"](https://www.baua.de/DE/Themen/Anwendungssichere-Chemikalien-und-Produkte/Produktsicherheit/Produktinformation/Datenbank/Produktsicherheit_dynnode.html), mit ein paar Ausnahmen, wo Hersteller / Märkte mit ihren Rückrufseiten verlinkt sind. Die Datenbank ist aber deutlich größer als die 52 Ergebnisse, die "product" zurückgibt.

**Comment by auchtetraborat** [comment]
Da es nun https://github.com/bundesAPI/lebensmittelwarnung-api/ gibt, für wie sinnvoll haltet ihr eine Integration von dem Scraper in deutschland?

**Comment by LilithWittmann** [comment]
Ich glaube erledigt 🎉
