### ISSUE TITLE
Inhalte des Bundesrats

### ISSUE THREAD

**Issue by Lukas2112** [bundesAPI/sofortmassnahmen#37]
Die notwendigen Infos lassen sich mit Sicherheit über die App finden: https://www.bundesrat.de/DE/service/app/app-node.html

**Comment by LilithWittmann** [comment]
Übersicht:
http://www.bundesrat.de/iOS/v3/startlist_table.xml?view=renderXml
Aktuelles:
http://www.bundesrat.de/iOS/v3/01_Aktuelles/aktuelles_table.xml?view=renderXml
Termine:
http://www.bundesrat.de/iOS/v3/02_Termine/termine_table.xml?view=renderXml
Plenum kompakt:
http://www.bundesrat.de/iOS/v3/03_Plenum/plenum_kompakt_table.xml?view=renderXml
Plenum aktuelle Sitzung: 
http://www.bundesrat.de/iOS/SharedDocs/3_Plenum/plenum_aktuelleSitzung_table.xml?view=renderXml
Plenum Chronologisch:
http://www.bundesrat.de/iOS/SharedDocs/3_Plenum/plenum_toChronologisch_table.xml?view=renderXml
Plenum nächste Sitzung:
https://www.bundesrat.de/iOS/SharedDocs/3_Plenum/plenum_naechsteSitzungen.xml?view=renderXml
Mitglieder:
http://www.bundesrat.de/iOS/SharedDocs/2_Mitglieder/mitglieder_table.xml?view=renderXml
Stimmverteilung:
http://www.bundesrat.de/iOS/v3/06_Stimmen/stimmverteilung.xml?view=renderXml
Präsidium:
http://www.bundesrat.de/iOS/v3/05_Bundesrat/Praesidium/bundesrat_praesidium.xml?view=renderXml

**Comment by LilithWittmann** [comment]
https://bundesrat.api.bund.dev/
