### ISSUE TITLE
Aktuelle Reisewarnungen des Auswärtigen Amtes als JSON?

### ISSUE THREAD

**Issue by Lukas2112** [bundesAPI/sofortmassnahmen#4]
Die aktuellen Reisewarnungen des Auswärtigen Amtes können derzeit "nur" als E-Mail-Newsletter und RSS-Feed abonniert werden.

Ich könnte mir vorstellen, dass es sinnvoll wäre, wenn sie kontinuierlich im JSON-Format zur Verfügung stehen würden, um z.B. für Flughäfen Werbung darüber zu generieren?

https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/10.2.8Reisewarnungen

**Comment by fossdd** [comment]
Auf jeden Fall wäre JSON als weiteres Format sehr wünschenswert. Jedoch gibt es bereits die RSS-Datei, die man auch anstelle der json nehmen könnte.

**Comment by Lukas2112** [comment]
ja, aber ich glaube JSON wäre angenehmer, als RSS, oder?

**Comment by LilithWittmann** [comment]
✅ https://travelwarning.api.bund.dev/
