### ISSUE TITLE
Fahndungen des BKA als JSON

### ISSUE THREAD

**Issue by Lukas2112** [bundesAPI/sofortmassnahmen#5]
Ich könnte mir vorstellen, dass es vielleicht sinnvoll wäre, wenn die Fahndungen des Bundeskriminalamtes (BKA), die auf der Homepage des BKAs (https://www.bka.de/SiteGlobals/Forms/Suche/Fahndungsliste_Personenfahndung_Formular.html;jsessionid=CC4150952B35776F80B8854E07C9127E.live2301?nn=3806) veröffentlicht werden als JSON-File abrufbar wären.

**Comment by 3nol** [comment]
Wir hätten einen Scraper für die Website unter https://github.com/3nol/bka

**Comment by LilithWittmann** [comment]
https://polizei.brandenburg.de/ipa_api/datenschutz

https://polizei.brandenburg.de/ipa_api/pegel/version/18
https://polizei.brandenburg.de/ipa_api/news/version/18

https://polizei.brandenburg.de/ipa_api/reviere/version/1
https://polizei.brandenburg.de/ipa_api/vwd/version/1
https://polizei.brandenburg.de/ipa_api/highlights/version/1
https://polizei.brandenburg.de/ipa_api/waldbrand/version/1
https://polizei.brandenburg.de/ipa_api/news/version/1?count=5000&category=8&district=500

**Comment by LilithWittmann** [comment]
https://interpol.api.bund.dev/
https://polizei.brandenburg.api.bund.dev/
