### ISSUE TITLE
Lobbyregister Bundestag

### ISSUE THREAD

**Issue by jfowl** [bundesAPI/sofortmassnahmen#53]
Vom Lobbyregister des Bundestags kann man sich Suchergebnisse (auch für alle Eintrage, also Suche nach "") und Einzelseiten als JSON herunterladen.

- GET `https://www.lobbyregister.bundestag.de/sucheJson?q=<QUERY>&sort=REGISTRATION_DESC`
- GET `https://www.lobbyregister.bundestag.de/sucheDetailJson?q=<QUERY>&sort=REGISTRATION_DESC`

Auch einzelne Ergebnisse können abgefragt werden:

- GET `https://www.lobbyregister.bundestag.de/sucheJson/R000180/37`

Die Dokumentation sollte aufgrund der Übersichtlichkeit der API nicht zu schwer sein, kann ich auch gerne mal machen.

Weiterführende Links:

- [Schema-Aufbau-Dokumentation als PDF](https://www.bundestag.de/resource/blob/874134/1ec62d1a7c015d2263e6de3a1e275405/Dokumentation-JSON-Downloads-data.pdf)
- [Änderungs-Tracking mit GitHub Actions](https://github.com/jfowl/bundestag-lobbyregister-changes)

**Comment by jfowl** [comment]
> Kannst du schon absehen, wann du dazu kommen wirst?

Ich setze mich jetzt mal daran, das kurz in eine OpenAPI spec umzuwandeln

**Comment by wirthual** [comment]
Hi,

Sehr coole Sache.

Hier gibt es ein [Repo Template](https://github.com/bundesAPI/api-doc-template) welches hilfreich sein kann :) 

Ist noch ziemlich neu, wenn ihr es verwendet und auf Probleme stosst, lasst es mich wissen :+1:

**Comment by wirthual** [comment]
Ich kann ein Repo unter BundesAPI erstellen das ihr forken koennt.

Was fuer ein Name wuerde hier sinn machen: bundestag-lobbyregister, lobbyregister-bundestag oder nur lobbyregister?

**Comment by jfowl** [comment]
> Was fuer ein Name wuerde hier sinn machen: bundestag-lobbyregister, lobbyregister-bundestag oder nur lobbyregister?

Da es schon einmal `bundestag-api` gibt, würde ich `bundestag-lobbyregister` vorschlagen.

**Comment by wirthual** [comment]
Jap da stimme ich dir zu. Hier ist ein repo dafuer:

[bundestag-lobbyregister](https://github.com/bundesAPI/bundestag-lobbyregister-api)

**Comment by jfowl** [comment]
Ich habe das Schema mal soweit vervollständigt, kommt zu normaleren Uhrzeiten noch mal per PR.

**Comment by wirthual** [comment]
Danke dir. Habs mal gemerged um zu schauen wos noch klemmt. 

Der Generator ist irgendwie mit DetailedSearchResults nicht zufrieden:

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute components.schemas.DetailedSearchResults.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:556)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:583)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
Liegt wahrscheinlich daran das er ein array statt ein object erwartet oder irgendwie anderstherum.

**Comment by jfowl** [comment]
Ich habe mal einige Dinge in https://github.com/bundesAPI/bundestag-lobbyregister-api/pull/2 ergänzt.
