### ISSUE TITLE
APIs der Bundesagentur für Arbeit

### ISSUE THREAD

**Issue by AndreasFischer1985** [bundesAPI/sofortmassnahmen#56]
Neben der [Jobsuche](https://github.com/bundesAPI/jobsuche-api), [Weiterbildungssuche](https://github.com/bundesAPI/weiterbildungssuche-api), [(Berufs-)Ausbildungssuche](https://github.com/AndreasFischer1985/ausbildungssuche-api), [Studiensuche](https://github.com/AndreasFischer1985/studiensuche-api) und dem [Entgeltatlas](https://github.com/AndreasFischer1985/weiterbildungssuche-api), die zwischenzeitlich dokumentiert wurden, finden sich auf [web.arbeitsagentur.de](https://web.arbeitsagentur.de) auch noch eine Reihe weiterer Schnittstellen der Bundesagentur für Arbeit, die noch nicht angemessen dokumentiert sind, z.B. 

- https://web.arbeitsagentur.de/ausbildungssuche/schulabschluss-suche
- https://web.arbeitsagentur.de/ausbildungssuche/vorbereitende-hilfen-suche
- ~~https://web.arbeitsagentur.de/sprachfoerderung/suche/berufssprachkurse~~
- ~~https://web.arbeitsagentur.de/sprachfoerderung/suche/anerkennungen~~
- ~~https://web.arbeitsagentur.de/sprachfoerderung/suche/sonstige-kurse~~
- ~~https://web.arbeitsagentur.de/coachingundaktivierung/suche~~

***Update:*** die durchgestrichenen Punkte wurden zwischenzeitlich bereits dokumentiert,

**Comment by wirthual** [comment]
Da gibt es ja so ne menge, da macht es fast sinn ein subpackage fuers arbeitsamt zu erstellen

**Comment by AndreasFischer1985** [comment]
Gerne. Bzgl. der API-Dokumentationen bin ich auch gerade am Überlegen, die ersten beiden (irgendwann mal) noch in die Dokumentation von ausbildungssuche-api zu integrieren und die nächsten drei in das heute angelegte repo berufssprachkurssuche-api. Das scheint zumindest der internen Gliederungslogik der Bundesagentur für Arbeit zu entsprechen, auch wenn ich es aktuell noch nicht so 100% gelungen finde.

**Comment by AndreasFischer1985** [comment]
Auch clientId und clientSecret scheinen im Sinne der vorgeschlagenen Zuordnung mit denen von ausbildungssuche-api und berufssprachkurssuche-api übereinzustimmen.

**Comment by AndreasFischer1985** [comment]
Ich habe soeben die Parameter sty (ausbildungssuche-api) bzw. systematiken (berufssprachkurssuche-api), dokumentiert, über die sich auch die Daten der noch ausstehenden o.g. Schnittstellen anfordern lassen (sowie außerdem noch https://web.arbeitsagentur.de/ausbildungssuche/begleitende-hilfen-suche).
