### ISSUE TITLE
Tagesschau API

### ISSUE THREAD

**Issue by AndreasFischer1985** [bundesAPI/sofortmassnahmen#57]
Passt eine Dokumentation der Tagesschau-API in das Programm von bund.dev?
Ich hätte [hier](https://github.com/AndreasFischer1985/tagesschau-api) mal eine angelegt.

**Comment by septatrix** [comment]
In dem Repository sind Issues nicht aktiviert. Könnte man diese erlauben?

**Comment by AndreasFischer1985** [comment]
Ja, kein Problem. Sind aktiviert.
