### ISSUE TITLE
Bundeshaushalt

### ISSUE THREAD

**Issue by anetz89** [bundesAPI/sofortmassnahmen#66]
Auf [Bundeshaushalt Digital](https://bundeshaushalt.de/DE/Bundeshaushalt-digital/bundeshaushalt-digital.html) kann man in eines interaktiven Diagramms den Soll und Ist-Haushalt der letzten Jahre erforschen. Das Durchklicken und Vergleichen ist recht mühsam, das kann man sicher mit einem Programm einfacher analysieren. Glücklicherweise stützt sich das Diagramm auf eine API, die ich versucht habe [hier](https://github.com/anetz89/bundeshaushalt-api) zu dokumentieren.
Gerne kopieren/erweitern/korrigieren/...

**Comment by wirthual** [comment]
Danke fuer deinen Beitrag. Hab die api beschreibung [hier](https://github.com/bundesAPI/bundeshaushalt-api) hinzugefuegt.
