### ISSUE TITLE
GKV-Hilfsmittelverzeichnis

### ISSUE THREAD

**Issue by jens-ox** [bundesAPI/sofortmassnahmen#67]
[**Link**](https://hilfsmittel.gkv-spitzenverband.de/home) | [Eintrag in VIP](https://www.verwaltungsdaten-informationsplattform.de/SharedDocs/Register/Pflegehilfsmittelverzeichnis.html)

Das GKV-Hilfsmittelverzeichnis ist eine Baumstruktur aus Produktgruppen und Produkten, die unter die Leistungspflicht der Kassen fallen.

Ist das eine API, die im Rahmen dieses Projekts dokumentiert werden soll? Strenggenommen sind das keine Daten des Bundes, sondern des Spitzenverbands GKV Bund. Das Verzeichnis gilt allerdings bundesweit und wird ja auch auf der Verwaltungsinformationsplattform geführt.

**Comment by wirthual** [comment]
Ich finde das passt.

**Comment by jens-ox** [comment]
Kannst du `hilfsmittel-api` anlegen?

**Comment by LilithWittmann** [comment]
https://github.com/bundesAPI/hilfsmittel-api

**Comment by jens-ox** [comment]
Umgesetzt 👍🏼
